prisma/schema.prisma, src/constants/index.ts, src/constants/responseMessage.ts, src/controller/index.ts, src/controller/teamController.ts, src/modules/makeTeamCode.ts, src/router/teamRouter.ts, src/service/index.ts, src/service/teamService.ts
close #1 
<br>
- 초대장  생성 api 구현
<br>
- 난수 생성해서 초대코드 생성
<br>
- 감사합니당 진짜 완줜
=> feat: 초대장 생성 api 구현

prisma/schema.prisma, src/constants/responseMessage.ts, src/controller/index.ts, src/controller/teamController.ts, src/modules/makeTeamCode.ts, src/router/index.ts, src/router/teamRouter.ts, src/service/index.ts, src/service/teamService.ts
close #3 
<br>
- 초대장으로 프로젝트 팀 입장 API를 구현
<br>
- teamId를 params에 담으려고 했으나, 초대링크에 숫자 자동증가인 teamId가 들어가면 보안문제가 생길 수 있어서 웹과 논의 후, teamCode를 params에 담기로 결정했습니다.
<br>
- 코드 읽어보고 궁금한 거나 잘못된 점 있으면 피드백 부탁드려요~
=> feat: 초대장으로 프로젝트 팀 입장 API 구현

prisma/schema.prisma, src/constants/responseMessage.ts, src/controller/chatController.ts, src/controller/index.ts, src/interfaces/createAnswerDto.ts, src/router/chatRouter.ts, src/router/index.ts, src/router/teamRouter.ts, src/service/chatService.ts, src/service/index.ts
close #5 
<br>
- 해피니스 체크 답변 받기 api 구현
<br>
- DTO를 이용해서 해피니스 체크 답변 받는 api를 구현했습니다. 
<br>
- 피드백 부탁드려요!!
=> feat: 해피니스 체크 답변 받기 api 구현

package.json, src/config/index.ts, src/controller/chatController.ts, src/controller/teamController.ts, src/modules/returnToSlackMessage.ts, src/modules/slackAPI.ts, yarn.lock
close #6 
- 슬랙을 활용하여 서버 에러 모니터링을 위해 Slack Webhook을 연동합니다.
- slackAPI 작성
- returnToSlackMessage 작성
- 같이 작업하느라 고생 많았어요 채영아~ 확인하는대로 머지해주세요!
=> feat: Slack Webhook 연동

src/constants/responseMessage.ts, src/controller/teamController.ts, src/router/teamRouter.ts, src/service/teamService.ts
close #10 
- 팀 해피니스 체크 유무를 확인합니다.
- responseMessage 작성
- router 작성
- controller 작성
- service 작성
- service 단을 중점적으로 봐주시면 좋을 거 같습니다! 궁금한 점이나 잘못된 점 있으면 피드백 부탁드립니다~
<br>
=> feat: 팀 해피니스 체크 유무 확인

package.json, prisma/schema.prisma, src/config/index.ts, src/constants/responseMessage.ts, src/controller/index.ts, src/controller/resultController.ts, src/router/index.ts, src/router/resultRouter.ts, src/service/index.ts, src/service/resultService.ts, yarn.lock
close #8 
<br>
- 개인 결과 뷰 조회하는 api
<br>
- router 작성
- controller 작성
- service 작성
<br>
- 피드백 부탁드려요!!
- <img width="1512" alt="스크린샷 2023-01-05 오후 9 18 20" src="https://user-images.githubusercontent.com/102947253/210778515-f480a7d0-1a4a-4b45-b7a0-fb99a384c9ab.png">
=> feat: 개인 결과 뷰 조회

src/controller/teamController.ts
close #13 
<br>
- 초대장(방) 생성 api 수정
<br>
- try catch 로 수정
<br>
- 머지해주세여!!
=> fix: 초대장(방) 생성 api

src/modules/makeTeamCode.ts
close #16 
<br>
- 팀 코드를 생성할때 절대 겹치지 않도록 Date 객체의 시간을 밀리초로 변환 -> 현재 밀리초를 36진수로 표현
<br>
- makeTeamCode 수정
<br>
- 머지해주세용~!
=> fix: 팀 코드 생성

src/constants/responseMessage.ts, src/controller/resultController.ts, src/router/resultRouter.ts, src/service/resultService.ts, src/service/teamService.ts
close #20 
- 팀 결과를 조회합니다.
- 작업 중, 웹 파트의 의견이 있어서 이번 브랜치에 반영하였습니다
- 궁금한 점, 잘못된 점 있으면 피드백 부탁드려요~
=> feat: 팀 결과 조회 API 구현

src/constants/responseMessage.ts, src/controller/resultController.ts, src/router/resultRouter.ts, src/service/resultService.ts
close #22 
<br>
- 팀 상세 결과를 조회 합니다.
<br>
- 데이터를 질문 번호별로 오름차순하였습니다
<br>
- 민재 API 개발 완료~ 마지막까지 화이팅!
=> feat: 팀 결과 상세 조회 성공 API 구현

prisma/schema.prisma, src/controller/chatController.ts, src/controller/resultController.ts, src/router/resultRouter.ts, src/service/chatService.ts, src/service/resultService.ts
close #18 
<br>
- 개인 해피니스 체크를 완료하면 완료했다고 표시합니다.
<br>
- router, controller, service 개발
<br>
- 수고했어요~!꺅
=> feat: 개인 해피니스 체크

.husky/pre-commit, package.json, src/router/chatRouter.ts, yarn.lock
close #27 
<br>
- husky 설정
<br>
- husky 설정
<br>
- 확인해주세요!!
=> add: husky 설정

src/constants/responseMessage.ts, src/controller/teamController.ts, src/service/teamService.ts
close #29 
- 프로젝트 방 입장 시, 닉네임 중복 체크합니다.
<br>
- service 단 duplicateName 함수 추가
-  controller 단 participateTeam에 duplicateName 추가
<br>
- 코드보고 궁금한 점이나 잘못된 점있으면 말씀해주세요~
=> feat: 프로젝트 방 입장 시, 닉네임 중복 체크

src/service/chatService.ts, src/service/resultService.ts, src/service/teamService.ts
close #31 
<br>
- service 단에서 try catch 적용 안된부분에 try catch 적용
<br>
- chatService, resultService, teamService에 try catch 적용
<br>
- 틀린 부분 있는지 확인해주쎄요!!
=> fix: try catch로 수정

package.json, src/controller/chatController.ts, src/controller/resultController.ts, src/controller/teamController.ts, src/middleware/errorValidator.ts, src/router/chatRouter.ts, src/router/resultRouter.ts, src/router/teamRouter.ts, src/service/resultService.ts, yarn.lock
close #32 
<br>
- 프로젝트에 express-validator를 적용합니다.
<br>
- middleware에 errorValidator를 추가해주었습니다.
- 잘못된 요청일 경우, middleware로 핸들링 하도록 처리하였습니다.~
<br>
- 확인해보고 궁금한 점 있으면 피드백 부탁드려요~
=> feat: express-validator 적용

prisma/schema.prisma, src/controller/chatController.ts, src/controller/resultController.ts, src/controller/teamController.ts, src/interfaces/DTO.ts, src/interfaces/createAnswerDto.ts, src/service/chatService.ts, src/service/resultService.ts, src/service/teamService.ts
close #35
- 세미나에서 배운 dto를 적용합니다.
<br>
- interface 폴더에 DTO 파일을 만들어 한꺼번에 관리하도록 하였습니다.
<br>
- 코드 확인 부탁드려요~
=> feat: Dto 적용

package.json, src/config/index.ts, src/index.ts, yarn.lock
close #37 
<br>
- cors 설정
<br>
- index.ts에 cors 설정 추가
<br>
- 확인하고 머지해주세요~!
=> feat: cors 설정

src/service/resultService.ts
close #39 
<br>
- 팀 상세결과 조회 반환 값을 수정합니다.
<br>
- DB 컬럼 이름 변경
<br>
- 머지해주세요~
=> fix: 팀 상세결과 조회 반환 값 수정

src/service/resultService.ts
close #41 
<br>
- 개인 결과뷰 조회 api 에서 questiontype이 나오지 않아서 수정!!
<br>
- resultService 수정
<br>
- 확인해주세요!!
=> fix: 개인 결과 뷰 조회 api 수정

src/index.ts
close #44
<br>
- 웹 파트 휴대폰 뷰 테스트를 위한 origin 주소를 추가합니다.
<br>
- allowedOrigins에 주소 추가하였습니다.
<br>
- 머지 부탁드려요~
=> fix: cors 허용 origin 주소 추가

.husky/pre-commit, __test__/chat.spec.ts, __test__/result.spec.ts, __test__/team.spec.ts, jest.config.js, package.json, src/babel.config.json, src/controller/chatController.ts, src/index.ts, src/server.ts, tsconfig.json, yarn.lock
close #46 
<br>
- jest 초기설정 및 맡은 api 테스트코드 작성
<br>
- chat, result, team 테스트코드 작성
<br>
- 확인하구 머지해즈세요~!
=> feat: jest 초기설정 및 맡은 api 테스트코드 작성

nodemon.json, src/config/index.ts, src/server.ts, src/service/resultService.ts, yarn.lock
close #48 
<br>
- 팀 결과 항목별 점수 조회를 수정합니다.
<br>
- 팀 점수의 전체 합이 아닌 평균 값을 조회하도록 수정하였습니다.
<br>
- 읽어보고 머지해주세요~
=> fix: 팀 결과 항목별 점수 조회 수정

index.ts, nodemon.json
close #50 
<br>
- nginx가 안돼요..
<br>
- server.ts -> index.ts 이름 수정, 폴더 위치 변경
<br>
- 머지해주세요.. 젭알..
=> fix: index.ts 경로 수정

nodemon.json
close #54 
<br>
- package.json 경로 수정합니다.
<br>
- package.json ./index.ts -> ./src/index.ts 로 변경합니다.
<br>
- 머지 부탁드려요!
=> chore: package.json 경로 수정

src/constants/responseMessage.ts, src/controller/chatController.ts, src/controller/resultController.ts, src/controller/teamController.ts, src/error/errorGenerator.ts, src/error/errorHandler.ts, src/index.ts, src/service/chatService.ts, src/service/resultService.ts, src/service/teamService.ts
close #58 
<br>
- 에러 핸들링을 리팩토링합니다.
<br>
- 관심사 분리 어쩌구를 통하여 모듈화시키고 중복된 코드를 제거합니다.
<br>
- 같이 열심히 코드 수정해줘서 고마워요~ SB Merge Please😊
=> fix: 에러 핸들링

src/index.ts
close #61 
<br>
- cors origin 주소 추가해주기~!
<br>
- cors origin 주소 추가함
<br>
- 머지해줘요 당장~
=> fix: cors origin 주소 추가

src/index.ts
close #68 
<br>
- index 파일 수정
<br>
- import router from './routers'
- cors 주소 수정~
<br>
- 감삼다
=> fix: index파일 수정

src/controllers/teamController.ts, src/services/teamService.ts
close #74 
<br>
- 프로젝트 팀 입장 중복 닉네임 로직 수정합니다
<br>
- 전체 인원에서 중복닉네임이 아닌 팀 내에서 중복닉네임을 검사합니다.
<br>
- 머지해주세요~
=> fix: 프로젝트 팀 입장 중복 닉네임 로직 수정

.husky/pre-commit, __test__/chat.spec.ts, __test__/result.spec.ts, __test__/team.spec.ts, server.ts, src/index.ts
close #72 
<br>
- 팀 정보 조회 api test 코드 추가
<br>
- 팀 정보 조회 api test 코드 추가
<br>
- 웹 붙이는거 끝나고 머지 부탁드려용~!
=> feat: test 코드 추가

.husky/pre-commit, package.json, prisma/schema.prisma, server.ts, src/config/auth.ts, src/config/index.ts, src/controllers/index.ts, src/controllers/userController.ts, src/index.ts, src/interfaces/SocialUser.ts, src/middleware/auth.ts, src/modules/constants/exceptionMessage.ts, src/modules/constants/index.ts, src/modules/constants/responseMessage.ts, src/modules/jwtHandler.ts, src/routers/index.ts, src/routers/userRouter.ts, src/services/index.ts, src/services/resultService.ts, src/services/teamService.ts, src/services/userService.ts, yarn.lock
close #76 
<br>
- 카카오, 구글 로그인 및 회원가입을 진행합니다.
<br>
- jwtHandler 추가
- axios로 카카오, 구글 사용자 정보 받아오기
- 사용자 정보로 받아와서 DB를 뒤져 있으면 로그인, 없으면 회원가입
- accessToken 유효기간 3시간 설정
<br>
- 코드 읽는데 도움되도록 주석을 달아놓았습니다. 참고해주세요!
- 궁금한 점이 있거나 잘못된 점이 있다면 언제든지 피드백 부탁드립니다.
=> feat: 소셜로그인 및 회원가입

prisma/schema.prisma, src/controllers/resultController.ts, src/interfaces/DTO.ts, src/modules/constants/responseMessage.ts, src/routers/resultRouter.ts, src/services/resultService.ts
close #80
<br>
- 개인 결과 조회 후 저장하는 api 구현
<br>
- db 테이블 추가
- router, service, controller
<br>
- 피드백 주세요ㅠ
=> feat: 개인 결과 저장 api

prisma/schema.prisma, src/routers/teamRouter.ts
close #84 
<br>
- 초대장으로 방 입장 시, Invalid userId 에러가 확인되어 수정합니다.
<br>
- router에 auth middleware 추가를 안해놓았었습니다.
<br>
- 머지해주세요!
=> fix: 초대장으로 방 입장 시 auth 로직 추가

src/routers/chatRouter.ts
close #88
<br>
- chat 정보 생성 API 시, auth 로직을 추가하지 않았습니다.
<br>
- router에 auth를 추가해주었습니다!
<br>
- 확인해주시고 머지 부탁드려요!!
=> fix: router에 auth 로직 추가

src/services/userService.ts
close #96 
<br>
- 지난 티타임 결과 보기 시, teamId 반환합니다
<br>
- teamId 반환하는 코드를 수정하였습니다.
<br>
- 확인해주시고 머지 부탁드려요!
=> fix: 지난 티타임 결과 보기 시, teamId 반환 로직 수정

src/controllers/index.ts, src/controllers/tokenController.ts, src/modules/constants/responseMessage.ts, src/routers/authRouter.ts, src/routers/index.ts
close #98 
<br>
- accessToken가 유효한지 검증합니다.
<br>
- authRouter 생성
- tokenController 생성
- responseMessage 추가
<br>
- 코드 확인해주시고 머지 부탁드려요~
=> feat: 토큰 유효성 검증 API

src/services/userService.ts
close #100 
<br>
- 지난 티타임 결과 보기 API 로직을 수정합니다.
<br>
- 사용자가 팀에 대한 정보가 없을 시, 빈 배열을 반환해줍니다.
<br>
- 확인해주시고 머지 부탁드려요~!
=> fix: 지난 티타임 결과 보기 API 로직 수정

package.json, src/config/index.ts, src/index.ts, src/routers/resultRouter.ts, yarn.lock
close #104 
<br>
- 에러 모니터링 툴 Sentry를 설정하고, 기본적인 웹 보안을 강화합니다.
<br>
- Sentry, helmet 라이브러리 추가
- Sentry 슬랙과 연동 및 코드 연동
- helmet 설정
<br>
- 급한거 아니니 확인해주시고 머지 부탁드려요~
=> feat: Sentry 설정
